---

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Run at 1:00 every day
    - cron: 0 1 * * *

jobs:
  build:

    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
        platform: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Configure Git
        run: |
          git config --global core.autocrlf false

      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      # We have a race condition.
      # In particular, we push doccmd to PyPI and then not long after we try to install
      # the pushed version.
      # Here, we give PyPI time to propagate the package.
      - name: Install doccmd from PyPI
        uses: nick-fields/retry@v3
        with:
          timeout_seconds: 20
          max_attempts: 20
          command: uv sync --refresh
        env:
          UV_PYTHON: ${{ matrix.python-version }}

      - name: Lint
        run: |
          uv run --extra=dev pre-commit run --all-files --hook-stage pre-commit --verbose
          uv run --extra=dev pre-commit run --all-files --hook-stage pre-push --verbose
          uv run --extra=dev pre-commit run --all-files --hook-stage manual --verbose
        env:
          UV_PYTHON: ${{ matrix.python-version }}

      - uses: pre-commit-ci/lite-action@v1.0.3
        if: always()
